"""add hold_expires_at to bookings

Revision ID: 78e61ba2749b
Revises: 309882a5b204
Create Date: 2026-02-28 17:52:12.821910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e61ba2749b'
down_revision: Union[str, None] = '309882a5b204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'hold_expires_at')
    # ### end Alembic commands ###
